.TH nfprofile 1 2004-06-30 "" ""
.SH NAME
nfprofile \- netflow profiler
.SH SYNOPSIS
.HP 5
.B nfprofile [options] 
.SH DESCRIPTION
.B nfprofile
is the netflow profiler program for NfSen.
It reads the netflow data from the files stored by nfcapd and creates
the corresponding output files for every channel required.
The man page will be updated in the final release.

.SH OPTIONS

.SH "RETURN VALUE"

.SH NOTES
nfprofile will be removed from future releases of nfdump and will move into NfSen.

.SH "SEE ALSO"
nfcapd(1), nfdump(1), nfreplay(1)
.SH BUGS

